// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://utpejltclnslmxrdsfkh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV0cGVqbHRjbG5zbG14cmRzZmtoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2MTQ4NzEsImV4cCI6MjA1NzE5MDg3MX0.mVL_BWpmY4BmoB4AtlHbTFUu1hjauXOROabtG-IrpC8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);